name: Test, Build and Redeploy

on:
  push:
    branches: [ master ]

jobs:
  docker:
    name: Build docker image and publish on Docker Hub
    runs-on: ubuntu-latest
    
    env:
      REPO: ${{ secrets.DOCKER_REPO }}
      CORS_ALLOWED_ORIGIN: ${{ secrets.CORS_ALLOWED_ORIGIN }}

    steps:
    - uses: actions/checkout@v2
      
    - name: Login to Docker Hub
      run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASS }}
      
    - name: Build the Docker image
      run: docker build --build-arg CORS_ALLOWED_ORIGIN=${{ secrets.CORS_ALLOWED_ORIGIN }} -t $REPO:latest -t $REPO:$(date +%s) .

    - name: Publish Docker image
      run: docker push $REPO
  
  redeploy:
    name: Call webhook for redeploy
    runs-on: ubuntu-latest
    needs: [docker]
    
    steps:
      - name: Invoke deployment hook
        uses: distributhor/workflow-webhook@v1
        env:
          webhook_url: ${{ secrets.WEBHOOK_URL }}
          webhook_secret: ${{ secrets.WEBHOOK_SECRET }}
